### ISSUE TITLE
请问一下详细的下载和安装程序是这样吗？

### ISSUE THREAD

**Issue by 47898077** [lyy289065406/ro-single-server#101]
我的理解网单一般需要客服端，客户端补丁，服务器端。
大佬你的这个仓库提供的应该是只有服务器端的文件对吗？
这就意味着我要先下你给的客户端和客户端补丁的百度云盘文件，然后安装客户端再覆盖上客户端补丁。
此后才按你提供的教程启动服务器端的那些程序才能通过客户端补丁中的登录器登录游戏，是吗？

**Comment by lyy289065406** [comment]
是的，你发现了宝藏

**Comment by 47898077** [comment]
> 是的，你发现了宝藏



> 是的，你发现了宝藏

其他都运行的很好，就是所有任务都是乱码。
请问是因为本身是韩服客户端没有翻译还是因为翻译了但是需要去论坛下文件覆盖呢还是其他原因呢？

**Comment by lyy289065406** [comment]
我不理解任务乱码是哪里乱码，游戏内？服务端编辑？
游戏内乱码是你补丁没打好
编辑乱码是编码问题，RO只能用GBK

**Comment by 47898077** [comment]
> 我不理解任务乱码是哪里乱码，游戏内？服务端编辑？
> 游戏内乱码是你补丁没打好
> 编辑乱码是编码问题，RO只能用GBK

游戏中的游戏任务描述文字是乱码，其他界面的文字都是正常的。
所以我疑惑是我补丁没打好还是本来这部分文字就没有翻译。
